"""support simulated analytics import

Revision ID: 5a37393e0b19
Revises: 9fd2ef332fdd
Create Date: 2026-06-04 22:43:24.856863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a37393e0b19'
down_revision: Union[str, Sequence[str], None] = '9fd2ef332fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_analytics_records', sa.Column('data_source', sa.String(length=50), nullable=False))
    op.add_column('sales_analytics_records', sa.Column('source_file', sa.String(length=255), nullable=True))
    op.add_column('sales_analytics_records', sa.Column('source_record_key', sa.String(length=100), nullable=True))
    op.alter_column('sales_analytics_records', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sales_analytics_records', 'order_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('sales_analytics_records', 'order_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_sales_analytics_records_data_source'), 'sales_analytics_records', ['data_source'], unique=False)
    op.create_index(op.f('ix_sales_analytics_records_source_record_key'), 'sales_analytics_records', ['source_record_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_analytics_records_source_record_key'), table_name='sales_analytics_records')
    op.drop_index(op.f('ix_sales_analytics_records_data_source'), table_name='sales_analytics_records')
    op.alter_column('sales_analytics_records', 'order_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sales_analytics_records', 'order_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('sales_analytics_records', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sales_analytics_records', 'source_record_key')
    op.drop_column('sales_analytics_records', 'source_file')
    op.drop_column('sales_analytics_records', 'data_source')
    # ### end Alembic commands ###
