"""create initial tables

Revision ID: 9fd2ef332fdd
Revises: 
Create Date: 2026-06-04 08:44:38.786593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd2ef332fdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('scheduled_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_orders_order_number'), 'customer_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_customer_orders_status'), 'customer_orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('store_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('production_start_date', sa.Date(), nullable=True),
    sa.Column('estimated_arrival_date', sa.Date(), nullable=True),
    sa.Column('actual_arrival_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('reserved_order_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_product_id'), 'inventory_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_items_status'), 'inventory_items', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_items_store_type'), 'inventory_items', ['store_type'], unique=False)
    op.create_table('customer_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_order_items_inventory_item_id'), 'customer_order_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_customer_order_items_order_id'), 'customer_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_customer_order_items_product_id'), 'customer_order_items', ['product_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('from_location', sa.String(length=100), nullable=True),
    sa.Column('to_location', sa.String(length=100), nullable=True),
    sa.Column('movement_reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_table('sales_analytics_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('store_type', sa.String(length=50), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['customer_order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', name='unique_sales_record_per_order_item')
    )
    op.create_index(op.f('ix_sales_analytics_records_inventory_item_id'), 'sales_analytics_records', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_sales_analytics_records_order_id'), 'sales_analytics_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_sales_analytics_records_order_item_id'), 'sales_analytics_records', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_sales_analytics_records_product_id'), 'sales_analytics_records', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_analytics_records_record_date'), 'sales_analytics_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_sales_analytics_records_sku'), 'sales_analytics_records', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_analytics_records_sku'), table_name='sales_analytics_records')
    op.drop_index(op.f('ix_sales_analytics_records_record_date'), table_name='sales_analytics_records')
    op.drop_index(op.f('ix_sales_analytics_records_product_id'), table_name='sales_analytics_records')
    op.drop_index(op.f('ix_sales_analytics_records_order_item_id'), table_name='sales_analytics_records')
    op.drop_index(op.f('ix_sales_analytics_records_order_id'), table_name='sales_analytics_records')
    op.drop_index(op.f('ix_sales_analytics_records_inventory_item_id'), table_name='sales_analytics_records')
    op.drop_table('sales_analytics_records')
    op.drop_index(op.f('ix_inventory_movements_inventory_item_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_customer_order_items_product_id'), table_name='customer_order_items')
    op.drop_index(op.f('ix_customer_order_items_order_id'), table_name='customer_order_items')
    op.drop_index(op.f('ix_customer_order_items_inventory_item_id'), table_name='customer_order_items')
    op.drop_table('customer_order_items')
    op.drop_index(op.f('ix_inventory_items_store_type'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_status'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_product_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customer_orders_status'), table_name='customer_orders')
    op.drop_index(op.f('ix_customer_orders_order_number'), table_name='customer_orders')
    op.drop_table('customer_orders')
    # ### end Alembic commands ###
