"""add replenishment and model run tables

Revision ID: c8643f107b5e
Revises: 5a37393e0b19
Create Date: 2026-06-04 23:50:35.720610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8643f107b5e'
down_revision: Union[str, Sequence[str], None] = '5a37393e0b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('target_column', sa.String(length=100), nullable=False),
    sa.Column('training_row_count', sa.Integer(), nullable=False),
    sa.Column('feature_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mae', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('r2', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('model_path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replenishment_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('store_type', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_inventory', sa.Integer(), nullable=False),
    sa.Column('available_inventory', sa.Integer(), nullable=False),
    sa.Column('incoming_inventory', sa.Integer(), nullable=False),
    sa.Column('inventory_supply', sa.Integer(), nullable=False),
    sa.Column('predicted_period_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('predicted_daily_sales', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('forecasted_demand_during_lead_time', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_delivery_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reorder_gap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('predicted_inventory_sales_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('suggested_reorder_quantity', sa.Integer(), nullable=False),
    sa.Column('replenishment_priority_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('replenishment_decision', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_run_id'], ['ml_model_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishment_recommendations_model_run_id'), 'replenishment_recommendations', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_product_id'), 'replenishment_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_sku'), 'replenishment_recommendations', ['sku'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_status'), 'replenishment_recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replenishment_recommendations_status'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_sku'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_product_id'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_model_run_id'), table_name='replenishment_recommendations')
    op.drop_table('replenishment_recommendations')
    op.drop_table('ml_model_runs')
    # ### end Alembic commands ###
